// Code generated by protoc-gen-go. DO NOT EDIT.
// source: preview.proto

package grpcapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PreviewParams struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width                uint32   `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreviewParams) Reset()         { *m = PreviewParams{} }
func (m *PreviewParams) String() string { return proto.CompactTextString(m) }
func (*PreviewParams) ProtoMessage()    {}
func (*PreviewParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_69892a06d40b231e, []int{0}
}

func (m *PreviewParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreviewParams.Unmarshal(m, b)
}
func (m *PreviewParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreviewParams.Marshal(b, m, deterministic)
}
func (m *PreviewParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreviewParams.Merge(m, src)
}
func (m *PreviewParams) XXX_Size() int {
	return xxx_messageInfo_PreviewParams.Size(m)
}
func (m *PreviewParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PreviewParams.DiscardUnknown(m)
}

var xxx_messageInfo_PreviewParams proto.InternalMessageInfo

func (m *PreviewParams) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PreviewParams) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PreviewParams) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Preview struct {
	Params               *PreviewParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Image                []byte         `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Preview) Reset()         { *m = Preview{} }
func (m *Preview) String() string { return proto.CompactTextString(m) }
func (*Preview) ProtoMessage()    {}
func (*Preview) Descriptor() ([]byte, []int) {
	return fileDescriptor_69892a06d40b231e, []int{1}
}

func (m *Preview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preview.Unmarshal(m, b)
}
func (m *Preview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preview.Marshal(b, m, deterministic)
}
func (m *Preview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preview.Merge(m, src)
}
func (m *Preview) XXX_Size() int {
	return xxx_messageInfo_Preview.Size(m)
}
func (m *Preview) XXX_DiscardUnknown() {
	xxx_messageInfo_Preview.DiscardUnknown(m)
}

var xxx_messageInfo_Preview proto.InternalMessageInfo

func (m *Preview) GetParams() *PreviewParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Preview) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func init() {
	proto.RegisterType((*PreviewParams)(nil), "PreviewParams")
	proto.RegisterType((*Preview)(nil), "Preview")
}

func init() { proto.RegisterFile("preview.proto", fileDescriptor_69892a06d40b231e) }

var fileDescriptor_69892a06d40b231e = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0x4a, 0x2d,
	0xcb, 0x4c, 0x2d, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2, 0xe7, 0xe2, 0x0d, 0x80, 0x08,
	0x04, 0x24, 0x16, 0x25, 0xe6, 0x16, 0x0b, 0x09, 0x70, 0x31, 0x97, 0x16, 0xe5, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x42, 0x22, 0x5c, 0xac, 0xe5, 0x99, 0x29, 0x25, 0x19, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x10, 0x8e, 0x90, 0x18, 0x17, 0x5b, 0x46, 0x6a, 0x66, 0x7a,
	0x46, 0x89, 0x04, 0x33, 0x58, 0x18, 0xca, 0x53, 0x72, 0xe7, 0x62, 0x87, 0x1a, 0x28, 0xa4, 0xc6,
	0xc5, 0x56, 0x00, 0x36, 0x14, 0x6c, 0x1a, 0xb7, 0x11, 0x9f, 0x1e, 0x8a, 0x55, 0x41, 0x50, 0x59,
	0x90, 0x05, 0x99, 0xb9, 0x89, 0xe9, 0xa9, 0x60, 0x0b, 0x78, 0x82, 0x20, 0x1c, 0x27, 0xce, 0x28,
	0xf6, 0xf4, 0xa2, 0x82, 0xe4, 0xc4, 0x82, 0xcc, 0x24, 0x36, 0xb0, 0x5b, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xda, 0x75, 0x75, 0xcd, 0xbc, 0x00, 0x00, 0x00,
}
