// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

package cache

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SavePreviewRequest struct {
	Preview              *Preview `protobuf:"bytes,1,opt,name=preview,proto3" json:"preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SavePreviewRequest) Reset()         { *m = SavePreviewRequest{} }
func (m *SavePreviewRequest) String() string { return proto.CompactTextString(m) }
func (*SavePreviewRequest) ProtoMessage()    {}
func (*SavePreviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{0}
}

func (m *SavePreviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavePreviewRequest.Unmarshal(m, b)
}
func (m *SavePreviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavePreviewRequest.Marshal(b, m, deterministic)
}
func (m *SavePreviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavePreviewRequest.Merge(m, src)
}
func (m *SavePreviewRequest) XXX_Size() int {
	return xxx_messageInfo_SavePreviewRequest.Size(m)
}
func (m *SavePreviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SavePreviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SavePreviewRequest proto.InternalMessageInfo

func (m *SavePreviewRequest) GetPreview() *Preview {
	if m != nil {
		return m.Preview
	}
	return nil
}

type SavePreviewResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SavePreviewResponse) Reset()         { *m = SavePreviewResponse{} }
func (m *SavePreviewResponse) String() string { return proto.CompactTextString(m) }
func (*SavePreviewResponse) ProtoMessage()    {}
func (*SavePreviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{1}
}

func (m *SavePreviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavePreviewResponse.Unmarshal(m, b)
}
func (m *SavePreviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavePreviewResponse.Marshal(b, m, deterministic)
}
func (m *SavePreviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavePreviewResponse.Merge(m, src)
}
func (m *SavePreviewResponse) XXX_Size() int {
	return xxx_messageInfo_SavePreviewResponse.Size(m)
}
func (m *SavePreviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SavePreviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SavePreviewResponse proto.InternalMessageInfo

func (m *SavePreviewResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetPreviewRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width                uint32   `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPreviewRequest) Reset()         { *m = GetPreviewRequest{} }
func (m *GetPreviewRequest) String() string { return proto.CompactTextString(m) }
func (*GetPreviewRequest) ProtoMessage()    {}
func (*GetPreviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{2}
}

func (m *GetPreviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPreviewRequest.Unmarshal(m, b)
}
func (m *GetPreviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPreviewRequest.Marshal(b, m, deterministic)
}
func (m *GetPreviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPreviewRequest.Merge(m, src)
}
func (m *GetPreviewRequest) XXX_Size() int {
	return xxx_messageInfo_GetPreviewRequest.Size(m)
}
func (m *GetPreviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPreviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPreviewRequest proto.InternalMessageInfo

func (m *GetPreviewRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetPreviewRequest) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *GetPreviewRequest) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetPreviewResponse struct {
	// Types that are valid to be assigned to Result:
	//	*GetPreviewResponse_Preview
	//	*GetPreviewResponse_Error
	Result               isGetPreviewResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetPreviewResponse) Reset()         { *m = GetPreviewResponse{} }
func (m *GetPreviewResponse) String() string { return proto.CompactTextString(m) }
func (*GetPreviewResponse) ProtoMessage()    {}
func (*GetPreviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{3}
}

func (m *GetPreviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPreviewResponse.Unmarshal(m, b)
}
func (m *GetPreviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPreviewResponse.Marshal(b, m, deterministic)
}
func (m *GetPreviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPreviewResponse.Merge(m, src)
}
func (m *GetPreviewResponse) XXX_Size() int {
	return xxx_messageInfo_GetPreviewResponse.Size(m)
}
func (m *GetPreviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPreviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPreviewResponse proto.InternalMessageInfo

type isGetPreviewResponse_Result interface {
	isGetPreviewResponse_Result()
}

type GetPreviewResponse_Preview struct {
	Preview *Preview `protobuf:"bytes,1,opt,name=preview,proto3,oneof"`
}

type GetPreviewResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetPreviewResponse_Preview) isGetPreviewResponse_Result() {}

func (*GetPreviewResponse_Error) isGetPreviewResponse_Result() {}

func (m *GetPreviewResponse) GetResult() isGetPreviewResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetPreviewResponse) GetPreview() *Preview {
	if x, ok := m.GetResult().(*GetPreviewResponse_Preview); ok {
		return x.Preview
	}
	return nil
}

func (m *GetPreviewResponse) GetError() string {
	if x, ok := m.GetResult().(*GetPreviewResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetPreviewResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetPreviewResponse_Preview)(nil),
		(*GetPreviewResponse_Error)(nil),
	}
}

func init() {
	proto.RegisterType((*SavePreviewRequest)(nil), "SavePreviewRequest")
	proto.RegisterType((*SavePreviewResponse)(nil), "SavePreviewResponse")
	proto.RegisterType((*GetPreviewRequest)(nil), "GetPreviewRequest")
	proto.RegisterType((*GetPreviewResponse)(nil), "GetPreviewResponse")
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor_5fca3b110c9bbf3a) }

var fileDescriptor_5fca3b110c9bbf3a = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x1d, 0xaa, 0x86, 0xf6, 0xa2, 0x4a, 0x70, 0xa9, 0xaa, 0x28, 0x53, 0x65, 0x31, 0x54,
	0x42, 0xf2, 0x50, 0x06, 0x10, 0x23, 0x0c, 0x74, 0x44, 0xe9, 0xca, 0x52, 0xca, 0x09, 0x47, 0xaa,
	0x70, 0xb0, 0x9d, 0x66, 0xe1, 0xc7, 0x23, 0xc7, 0x0e, 0x04, 0x02, 0x9b, 0xdf, 0xf9, 0x9e, 0xef,
	0xbb, 0x67, 0x48, 0xf6, 0xbb, 0xbd, 0x24, 0x51, 0x69, 0x65, 0x55, 0x3e, 0xab, 0x34, 0x1d, 0x4b,
	0x6a, 0xbc, 0xe4, 0x37, 0x80, 0xdb, 0xdd, 0x91, 0x1e, 0x7d, 0xb1, 0xa0, 0xf7, 0x9a, 0x8c, 0x45,
	0x0e, 0xa7, 0xa1, 0x2d, 0x8b, 0x96, 0xd1, 0x2a, 0x59, 0x4f, 0x44, 0xd7, 0xd1, 0x5d, 0xf0, 0x4b,
	0x48, 0x7f, 0x38, 0x4d, 0xa5, 0xde, 0x0c, 0xe1, 0x1c, 0xc6, 0xa4, 0xb5, 0xd2, 0xad, 0x71, 0x5a,
	0x78, 0xc1, 0xb7, 0x70, 0xfe, 0x40, 0xf6, 0xd7, 0x94, 0x33, 0x18, 0xd5, 0xfa, 0x10, 0x1a, 0xdd,
	0xd1, 0x99, 0x9b, 0xf2, 0xc5, 0xca, 0xec, 0x64, 0x19, 0xad, 0x66, 0x85, 0x17, 0xb8, 0x80, 0x58,
	0x52, 0xf9, 0x2a, 0x6d, 0x36, 0x6a, 0xcb, 0x41, 0xf1, 0x27, 0xc0, 0xfe, 0xa3, 0x01, 0xe0, 0xe2,
	0x5f, 0xf6, 0x0d, 0xfb, 0xa2, 0xc7, 0x45, 0x87, 0xe9, 0x26, 0x4d, 0x37, 0x2c, 0x80, 0xde, 0x4d,
	0x20, 0xd6, 0x64, 0xea, 0x83, 0x5d, 0x7f, 0xc0, 0xf8, 0xde, 0xe5, 0x86, 0xb7, 0x90, 0xf4, 0x16,
	0xc5, 0x54, 0x0c, 0x03, 0xcb, 0xe7, 0xe2, 0x8f, 0x2c, 0x38, 0xc3, 0x6b, 0x80, 0x6f, 0x44, 0x44,
	0x31, 0x08, 0x21, 0x4f, 0xc5, 0x70, 0x07, 0xce, 0x9e, 0xe3, 0xf6, 0x7b, 0xae, 0x3e, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xed, 0xa4, 0xbe, 0x03, 0xbc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CacheClient is the client API for Cache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CacheClient interface {
	SavePreview(ctx context.Context, in *SavePreviewRequest, opts ...grpc.CallOption) (*SavePreviewResponse, error)
	GetPreview(ctx context.Context, in *GetPreviewRequest, opts ...grpc.CallOption) (*GetPreviewResponse, error)
}

type cacheClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheClient(cc grpc.ClientConnInterface) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) SavePreview(ctx context.Context, in *SavePreviewRequest, opts ...grpc.CallOption) (*SavePreviewResponse, error) {
	out := new(SavePreviewResponse)
	err := c.cc.Invoke(ctx, "/Cache/SavePreview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) GetPreview(ctx context.Context, in *GetPreviewRequest, opts ...grpc.CallOption) (*GetPreviewResponse, error) {
	out := new(GetPreviewResponse)
	err := c.cc.Invoke(ctx, "/Cache/GetPreview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheServer is the server API for Cache service.
type CacheServer interface {
	SavePreview(context.Context, *SavePreviewRequest) (*SavePreviewResponse, error)
	GetPreview(context.Context, *GetPreviewRequest) (*GetPreviewResponse, error)
}

// UnimplementedCacheServer can be embedded to have forward compatible implementations.
type UnimplementedCacheServer struct {
}

func (*UnimplementedCacheServer) SavePreview(ctx context.Context, req *SavePreviewRequest) (*SavePreviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SavePreview not implemented")
}
func (*UnimplementedCacheServer) GetPreview(ctx context.Context, req *GetPreviewRequest) (*GetPreviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPreview not implemented")
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_SavePreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).SavePreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cache/SavePreview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).SavePreview(ctx, req.(*SavePreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_GetPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).GetPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cache/GetPreview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).GetPreview(ctx, req.(*GetPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SavePreview",
			Handler:    _Cache_SavePreview_Handler,
		},
		{
			MethodName: "GetPreview",
			Handler:    _Cache_GetPreview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache.proto",
}
