// Code generated by protoc-gen-go. DO NOT EDIT.
// source: previewer.proto

package previewer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_36d271fa454b3456, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type MakePreviewRequest struct {
	Params               *PreviewParams    `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MakePreviewRequest) Reset()         { *m = MakePreviewRequest{} }
func (m *MakePreviewRequest) String() string { return proto.CompactTextString(m) }
func (*MakePreviewRequest) ProtoMessage()    {}
func (*MakePreviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36d271fa454b3456, []int{1}
}

func (m *MakePreviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakePreviewRequest.Unmarshal(m, b)
}
func (m *MakePreviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakePreviewRequest.Marshal(b, m, deterministic)
}
func (m *MakePreviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakePreviewRequest.Merge(m, src)
}
func (m *MakePreviewRequest) XXX_Size() int {
	return xxx_messageInfo_MakePreviewRequest.Size(m)
}
func (m *MakePreviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakePreviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakePreviewRequest proto.InternalMessageInfo

func (m *MakePreviewRequest) GetParams() *PreviewParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *MakePreviewRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type MakePreviewResponse struct {
	Preview              *Preview `protobuf:"bytes,1,opt,name=preview,proto3" json:"preview,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakePreviewResponse) Reset()         { *m = MakePreviewResponse{} }
func (m *MakePreviewResponse) String() string { return proto.CompactTextString(m) }
func (*MakePreviewResponse) ProtoMessage()    {}
func (*MakePreviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36d271fa454b3456, []int{2}
}

func (m *MakePreviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakePreviewResponse.Unmarshal(m, b)
}
func (m *MakePreviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakePreviewResponse.Marshal(b, m, deterministic)
}
func (m *MakePreviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakePreviewResponse.Merge(m, src)
}
func (m *MakePreviewResponse) XXX_Size() int {
	return xxx_messageInfo_MakePreviewResponse.Size(m)
}
func (m *MakePreviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakePreviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakePreviewResponse proto.InternalMessageInfo

func (m *MakePreviewResponse) GetPreview() *Preview {
	if m != nil {
		return m.Preview
	}
	return nil
}

func (m *MakePreviewResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*MakePreviewRequest)(nil), "MakePreviewRequest")
	proto.RegisterMapType((map[string]string)(nil), "MakePreviewRequest.HeadersEntry")
	proto.RegisterType((*MakePreviewResponse)(nil), "MakePreviewResponse")
}

func init() { proto.RegisterFile("previewer.proto", fileDescriptor_36d271fa454b3456) }

var fileDescriptor_36d271fa454b3456 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x65, 0x53, 0x4d, 0xec, 0xc4, 0xaa, 0x8c, 0x1e, 0x42, 0x2f, 0x86, 0x1c, 0x24, 0xa7, 0x45,
	0xe2, 0x45, 0x72, 0x17, 0xbc, 0x08, 0x65, 0xbc, 0x79, 0x5b, 0xed, 0x80, 0x52, 0x6d, 0xe2, 0xee,
	0xa6, 0xda, 0xff, 0xf2, 0x03, 0xa5, 0xb3, 0x1b, 0x50, 0x7a, 0x7b, 0xf3, 0xde, 0xcc, 0x9b, 0xc7,
	0x83, 0xd3, 0xde, 0xf2, 0xe6, 0x8d, 0xbf, 0xd8, 0xea, 0xde, 0x76, 0xbe, 0x9b, 0xcf, 0x22, 0x11,
	0xc6, 0xea, 0x1a, 0xd2, 0x47, 0x6f, 0xfc, 0xe0, 0x10, 0xe1, 0xe0, 0xa5, 0x5b, 0x72, 0xa1, 0x4a,
	0x55, 0xcf, 0x48, 0xf0, 0x8e, 0xf3, 0xfc, 0xed, 0x8b, 0xa4, 0x54, 0xf5, 0x94, 0x04, 0x57, 0x3f,
	0x0a, 0xf0, 0xc1, 0xac, 0x78, 0x11, 0x7c, 0x88, 0x3f, 0x07, 0x76, 0x1e, 0xaf, 0x20, 0xed, 0x8d,
	0x35, 0x1f, 0x4e, 0x0c, 0xf2, 0xe6, 0x44, 0xc7, 0x85, 0x85, 0xb0, 0x14, 0x55, 0x6c, 0x21, 0x7b,
	0x65, 0xb3, 0x64, 0xeb, 0x8a, 0xa4, 0x9c, 0xd4, 0x79, 0x53, 0xea, 0x7d, 0x37, 0x7d, 0x1f, 0x56,
	0xee, 0xd6, 0xde, 0x6e, 0x69, 0x3c, 0x98, 0xb7, 0x70, 0xfc, 0x57, 0xc0, 0x33, 0x98, 0xac, 0x78,
	0x2b, 0x0f, 0xa7, 0xb4, 0x83, 0x78, 0x01, 0x87, 0x1b, 0xf3, 0x3e, 0x70, 0x4c, 0x1c, 0x86, 0x36,
	0xb9, 0x55, 0xd5, 0x13, 0x9c, 0xff, 0xfb, 0xe3, 0xfa, 0x6e, 0xed, 0x18, 0x2b, 0xc8, 0x62, 0x21,
	0x31, 0xf7, 0xd1, 0x98, 0x9b, 0x46, 0x01, 0x2f, 0x21, 0x75, 0xd2, 0x91, 0xb8, 0xe6, 0x4d, 0xa6,
	0x43, 0x65, 0x14, 0xe9, 0xe7, 0x54, 0xba, 0xbc, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x72, 0x54,
	0x53, 0x76, 0x6d, 0x01, 0x00, 0x00,
}
